services:
  - type: web
    name: movie-recommender
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6

