services:
  - type: web
    name: movie-recommender
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    runtime: python-3.11.9

